### ISSUE TITLE
Is it possible to drag and drop between different tree? 

### ISSUE THREAD

**Issue by HananoshikaYomaru** [minop1205/react-dnd-treeview#101]
If it is possible, is there a guide on how to achieve this ?

**Comment by minop1205** [comment]
At the moment, drag-and-drop between different trees is not possible.
We are considering supporting this in the future, but I don't think it will be possible anytime soon.

**Comment by HananoshikaYomaru** [comment]
https://user-images.githubusercontent.com/43137033/151507638-84a888cd-0639-4e56-a522-1e62c46272d9.mp4



Em... I think it is possible. But it will required advanced skills of React and deep understanding of your package. Surely you can make it easier for user to implement this. 

# mechanism

The mechanism of determining whether the item can be dropped to a tree is based on a function `canDrop` of the `Tree` component. The default implementation is to search the item in the tree and see if the item can be found in the tree. The item can be dropped if it is in the same tree. Therefore, if you have two tree with same tree data, you can make the cross dropping work. 

The first step to make cross-tree dropping work is to pass your own `canDrop` property to the tree. Then you will see a lot of error because the items are not in same tree. But you can make that works if you solve all the errors.

# btw

Thanks for this lib. It is very beautiful and the code is cleanly written. ✨

**Comment by lpagliari** [comment]
@HananoshikaYomaru I was trying to implement the same on my current project, and I found a workaround that might work for some people while this lib does not implemente the feature.

What I did was to provide the items of both trees _to both trees_, and to set a different `rootId` as the parent of the items that did not belong to the given tree. This makes the `<Tree>` hide the items with the different root id, but keep them on the tree data, so the validations work fine.

Something like this:

```tsx
const rootIdOfTree1 = 1;
const rootIdOfTree2 = 2;
const itemsOfTree1 = originalItemsOfTree1.map(item => ({ ...item, parent: rootIdOfTree1 });
const itemsOfTree2 = originalItemsOfTree2.map(item => ({ ...item, parent: rootIdOfTree2 });

// When rendering tree1:
<Tree
  tree={[...itemsOfTree1, ...itemsOfTree2]}
  rootId={rootIdOfTree1}
/>

// When rendering tree2:
<Tree
  tree={[...itemsOfTree1, ...itemsOfTree2]}
  rootId={rootIdOfTree2}
/>
```

This is, of course, not a proper solution, just a workaround. But at least you might be able to keep using this lib and have the DnD between trees. I hope it works for you!

BTW, I second what you said: this is indeed a really nice lib, with a great API and very clean code. Congrats, @minop1205 , and thank you!

**Comment by HananoshikaYomaru** [comment]
This looks much simpler than my implementation. But to show the dropped node from another tree, we need to change the root id of the dropped node, right?

**Comment by lpagliari** [comment]
> This looks much simpler than my implementation. But to show the dropped node from another tree, we need to change the root id of the dropped node, right?

Do you mean "to show the placeholder while dragging the node to the other tree"? Or "to show the node on the tree _after_ the node was dropped"?

On the first case you might need to change the `canDrop`, although I believe you won't need to on most of the scenarios; on the second case: yes, you do need to change the root id of the dropped node on the `onDrop` for the node to appear on the tree.

**Comment by HananoshikaYomaru** [comment]
Yes, eventually the `canDrop` and `onDrop` will determine the cross-tree drag and drop behaviour. But I do think making every tree store every data will be easier for people to implement. But if you can perfectly control your `canDrop`, whether which tree hold what data will not be a big issue.
