### ISSUE TITLE
Prevent dragging nodes to the root

### ISSUE THREAD

**Issue by MrPrometheus** [minop1205/react-dnd-treeview#104]
Hello, I have a tree with 1 root node, all other nodes come from 1 root node. 

How can I make it so that any node below the 1st level cannot be dragged to the first level?

**Comment by minop1205** [comment]
@MrPrometheus 
Drop availability can be controlled by the canDrop callback.
https://github.com/minop1205/react-dnd-treeview#candrop-callback

Here is sample.
https://codesandbox.io/s/issue-104-h8vzt0?file=/src/App.tsx

**Comment by MrPrometheus** [comment]
Thank you!!!
