### ISSUE TITLE
Dependency issue, rdndmb-html5-to-touch introduces conflicts to touch events of dropdown when a tree is rendered in the DOM ANTD selects

### ISSUE THREAD

**Issue by ff-randy** [minop1205/react-dnd-treeview#106]
Issue:
As the title says if the Tree component is rendered then all of the "Selects" in the current DOM stops working. When you click on them they open up but closes immediately. 

Expected:
Selects/Dropdowns continue to work as usual.

Solution:
It is possible that the solutions will be to update a dependency https://github.com/LouisBrunner/dnd-multi-backend/tree/main/packages/rdndmb-html5-to-touch the owner released a new version about a year ago.

Thanks

**Comment by minop1205** [comment]
`rdndmb-html5-to-touch` has been removed as a dependency since @minoru/react-dnd-treeview v2.

I just checked the behavior using antd `Select` and the problem you mentioned did not occur.

If you continue to have problems, please reopen this issue.
