### ISSUE TITLE
Feature: drag from and drop to callback/handle

### ISSUE THREAD

**Issue by virus2016** [minop1205/react-dnd-treeview#11]
Hi there,

It would be great to get a specific onDropItem handle on each node to get the from and to.

Example

```
{
  from: {
    id: 2,
    parent: 1,
    droppable: false,
    text: 'File 1-1',
  },
  to: {
    id: 4,
    parent: 0,
    droppable: true,
    text: 'Folder 2',
  }
}
```

Is this possible?

**Comment by minop1205** [comment]
@virus2016 Thanks for the message!

You can't set up event handlers on each node right now, but you can use the onDrop callback of the TreeView component to get the dragSource and dropTarget.

https://github.com/minop1205/react-dnd-treeview#ondrop-callback

```
const [treeData, setTreeData] = useState(initialTreeData);
const handleDrop = (newTree, {dragSourceId, dropTargetId, dragSource, dropTarget}) => {

  // Do something

  setTreeData(newTree);
};

return (
  <Tree
    {...props}
    tree={treeData}
    onDrop={handleDrop}
  />
);
```

These dragSource and dropTarget correspond to the from and to you are talking about, but is this not enough?

What the case would you need to add an event handler to each node?
If it would make it easier to use, I would consider adding the feature.

**Comment by virus2016** [comment]
@minop1205 thank you for this! I didn't read your ondrop callback, my fault however, It's amazing! 

Great work on this project! We are starting to use it now.

**Comment by minop1205** [comment]
@virus2016 
You are welcome.
I'm glad I could help!
