### ISSUE TITLE
Rename package name

### ISSUE THREAD

**Issue by percy507** [minop1205/react-dnd-treeview#111]
Just a suggestion!!!

This package is more like a frame to build custom treeview instead of a component which can be directly use. So how about rename the package name to `react-treeview-frame`? 😂

Or you can consider to make some preset, beatuiful, directly-useable component in the future.

> https://mui.com/zh/x/
> 
> <img width="418" alt="image" src="https://user-images.githubusercontent.com/18365078/162309692-9b29bd59-4a3a-4053-8a16-4f3b77e26577.png">

**Comment by minop1205** [comment]
@percy507 Thank you for your suggestion!

As a package name, we would like to include the word `dnd`, which is a feature of this component. Also, it certainly resembles a frame, but we are rather making it with the following headless UI in mind.
https://headlessui.dev/react/menu

Therefore, while we appreciate your suggestion, we do not intend to change the name at this time.

As for the preset UI, it might be a good idea to release a related package separately from this package to avoid installing packages that will not be used.

My basic idea is to keep this package as thin and simple as possible.
