### ISSUE TITLE
Add the parent index and the current node index to props

### ISSUE THREAD

**Issue by zetorby** [minop1205/react-dnd-treeview#119]
How can get the index of the parent and the current node to number such a list?
![image](https://user-images.githubusercontent.com/20907230/171608131-92fa821d-775f-43bb-bdce-e095ee8295ec.png)

**Comment by minop1205** [comment]
@zetorby 
Even if parent index or current index is given to render, it may not be enough to obtain the expected prefix if the tree hierarchy is deep.

In any case, it is necessary to go back to the root node to get the index of each hierarchy, so please implement the logic in your application as shown in the example below.

https://codesandbox.io/s/issue-119-l81c14?file=/src/App.tsx

**Comment by zetorby** [comment]
@minop1205 Thank you for your help
