### ISSUE TITLE
Open Folder Option

### ISSUE THREAD

**Issue by younes-barhouni** [minop1205/react-dnd-treeview#12]
Hi,
I was playing with this component and my remark is it would be great if add open option in tree data in order to open a folder on initial load

**Comment by minop1205** [comment]
You're right, there are likely use cases where it's necessary.
Right now, everything is initially closed, so I'll consider implementing it to pass an array of node IDs to be opened in advance.

**Comment by bcheidemann** [comment]
This would be super useful!

**Comment by minop1205** [comment]
Merged: https://github.com/minop1205/react-dnd-treeview/pull/16

**Comment by minop1205** [comment]
@younes-barhouni 
I have addressed this issue by adding an API named initialOpen.
If you specify a Boolean value like the following, all folders will be opened initially.

```
<Tree
  {...props}
  initialOpen={true}
/>
```

Alternatively, you can pass an array of IDs as follows to initialize only specific nodes as open.

```
<Tree
  {...props}
  initialOpen={[1, 2, 3]}
/>
```

I have already released it as v1.1, so you can use it by updating the package.
Please let me know if you have any problems.

**Comment by minop1205** [comment]
Here's a sample.
https://codesandbox.io/s/initialize-with-open-parents-ts-9nkw3

**Comment by bcheidemann** [comment]
Thanks dude, that was fast! Have you already published a new npm version?

EDIT: never mind - I can see you've released a new version =)
