### ISSUE TITLE
Add a custom element to the end of the list (ul)

### ISSUE THREAD

**Issue by zetorby** [minop1205/react-dnd-treeview#120]
How to add a custom element to the end of the list (ul) ? Example,  add button of end list (ul)...

**Comment by minop1205** [comment]
@zetorby Currently there is no such API.
Buttons should be placed outside of Treeview(ul).
Is the following demo helpful? 

https://minop1205.github.io/react-dnd-treeview/?path=/story/examples-tree-add-remove-duplicate-nodes--add-remove-duplicate-nodes-story

**Comment by zetorby** [comment]
> @zetorby Currently there is no such API. Buttons should be placed outside of Treeview(ul). Is the following demo helpful?
> 
> https://minop1205.github.io/react-dnd-treeview/?path=/story/examples-tree-add-remove-duplicate-nodes--add-remove-duplicate-nodes-story

I need to add buttons exactly inside the tree
![image](https://user-images.githubusercontent.com/20907230/172617720-2c174bc3-4a20-47cd-a5c6-c7ecbf44e0cd.png)

**Comment by minop1205** [comment]
@zetorby 
Since this seems to be a special use case, I think it should be implemented on the application side rather than as an API.

One possible implementation would be to check the position of each node in the `render` API and add a button if it is the last node in the list.

Would the following sample be helpful?
https://codesandbox.io/s/issue-120-jq2o7t?file=/src/App.tsx

**Comment by zetorby** [comment]
> @zetorby Since this seems to be a special use case, I think it should be implemented on the application side rather than as an API.
> 
> One possible implementation would be to check the position of each node in the `render` API and add a button if it is the last node in the list.
> 
> Would the following sample be helpful? https://codesandbox.io/s/issue-120-jq2o7t?file=/src/App.tsx

**Comment by zetorby** [comment]
Yes, that will do, thank you for your help.
