### ISSUE TITLE
Prevent showing placeholder for current element's position while dragging

### ISSUE THREAD

**Issue by ngocducdim** [minop1205/react-dnd-treeview#122]
Hi, I have a problem, when I re-order the element, the placeholder alway show the element's current position (you can see the video, when I drag to bottom direction, the placeholder is showing but that position is current element's position) I don't want this behavior, is there anyway to prevent this?

https://user-images.githubusercontent.com/97713182/175512250-475ed32e-316f-452d-8ea5-2e94091db7ed.mp4

**Comment by minop1205** [comment]
@ngocducdim 
It is probably not possible with just the current parameters of the placeholderRender API.
If we can add the hovered node ID to the parameter of the placeholderRender API, it would be possible to determine.

**Comment by ngocducdim** [comment]
Ok thank you for the reply
