### ISSUE TITLE
max depth

### ISSUE THREAD

**Issue by aydozgeee** [minop1205/react-dnd-treeview#127]
Hello,
I added drag and drop feature to my project using dnd tree. I want the tree to have a max depth of 1. (i.e. there can only be one folder in a folder).I don't want it to be dropable when greater than that. how can I do it?

You can find the structure that I want to achieve in the attachment..

xt![dndtree](https://user-images.githubusercontent.com/101804555/180718312-70eb6fee-71a8-4473-aace-5eeb6f371ec3.jpeg)
?

**Comment by minop1205** [comment]
@punisher28 Thanks for your comment!

I have had a similar Issue in the past, please refer to this one.
https://github.com/minop1205/react-dnd-treeview/issues/62

If you are unable to resolve the issue, please reopen it.

**Comment by aydozgeee** [comment]
Hello @minop1205,
Thanks for your reply. I checked the solution that you shared but it was not the exact solution that I am looking for. After a bit of digging, I come up with a solution below. I will be happy if you share your thoughts about the solution.

https://codesandbox.io/s/otupwe

**Comment by minop1205** [comment]
@punisher28 The sample you provided is fine also.

I think it can be implemented a bit simpler, since we only need to know the depth of the dropTarget and the type of dragSource in the canDrop callback. Would this sample be helpful?

https://codesandbox.io/s/issue-127-fkfi1y?file=/src/App.jsx
