### ISSUE TITLE
Helow, how are you? First of all, congratulate you all with this amazing tool that you are developing. I want to know a bit more in detail, is there a possibility o you are planning to use all the back functionalities and give a different layout? Like Organizational charts? Kind regards and keep doing this amazing job!

### ISSUE THREAD

**Issue by Rvalle23** [minop1205/react-dnd-treeview#128]
# 機能要望

## 概要

例: テキストが見切れている箇所にはマウスオーバーでツールチップを表示する

## 目的・理由

例: タイトルの一覧表示などでテキストが見切れていると、詳細画面に遷移しないとタイトル全体が確認できないため

## 実装案があれば

例:
ツールチップには Material-UI tooltip を使用する。
文字数だけでなく画面リサイズにも対応すべきなので、ResizeObserver を使用するなどしてテキストの見切れ判定を行う。

## 参考情報

参考 URL などあれば

**Comment by minop1205** [comment]
@Rvalle23 Thank you for your comment!

This library outputs only a tree structure with `ul` and `li`, and style and layout must be defined by the library user.

As shown in the example below, it is possible to use CSS for layout.

https://codesandbox.io/s/minimum-configuration-js-forked-whzumj?file=/src/sample_data.json

If you need to draw lines connecting each node, as in the organization chart, you will need to be creative.
