### ISSUE TITLE
Disable Sorting & Drag/Drop Between Nodes

### ISSUE THREAD

**Issue by bcheidemann** [minop1205/react-dnd-treeview#13]
Hi,

I was just wondering if there was a way to disable the automatic sorting of the nodes or to provide a n order in which I want them to be sorted e.g. an index property on the node would be great. I didn't see anything in the docs so unless I'm missing anything I guess this is a feature request! =P

Additionally, it would be great if you supported dropping between nodes - this would be really useful in combination with the above feature request - especially for my use case!

Thanks,

Ben

**Comment by minop1205** [comment]
Right Now, The nodes are automatically sorted by name. You're right, there are likely use cases where we need to disable sorting or customize the sorting method, so we'll look into how to implement that.

As for dragging and dropping between nodes, it is a standard feature of this component, but is there any feature I am missing?

For example, in the following sample, drag and drop is possible.
https://codesandbox.io/s/full-features-js-itczn

**Comment by bcheidemann** [comment]
Hi, I hope you don't mind but I've taken the liberty to make a PR for this issue. Let me know if there's any modifications you'd like made. =)

**Comment by minop1205** [comment]
Thank you your contribute!!
I merged your PR. and I committed some tests too.

After responding to the following issue, I will publish to npm as a new version.
https://github.com/minop1205/react-dnd-treeview/issues/12

**Comment by bcheidemann** [comment]
Thanks!

**Comment by minop1205** [comment]
@bcheidemann 
I have released it as v1.1, so you can use it by updating the package.
If you have any problems, please create a new issue.

Thank you very much.

**Comment by bcheidemann** [comment]
Thanks, that's great to hear! I can't wait to use this in our project =)

EDIT: forgot to say - awesome work with this project by the way!
