### ISSUE TITLE
Can't we use hierarchical structure json data instead of flattern?

### ISSUE THREAD

**Issue by jeevasusej** [minop1205/react-dnd-treeview#142]
Can't we use hierarchical structure json data as below one instead of flattern?

![image](https://user-images.githubusercontent.com/19813131/190989810-bae19e50-eade-4740-b5c1-1340fdad5af4.png)

**Comment by minop1205** [comment]
@jeevasusej 
Since the structure of the data is directly related to the implementation of the component, data structures other than those described in the README cannot be used.

Before passing data to a component, please perform some kind of conversion to make it flat before use.
