### ISSUE TITLE
Make Drag and drop as optional?

### ISSUE THREAD

**Issue by jeevasusej** [minop1205/react-dnd-treeview#143]
Can we make drag and drop as optional?

**Comment by minop1205** [comment]
@jeevasusej 
Although there is no dedicated API, similar functionality can be achieved using the `canDrag` and `canDrop` APIs.

Please refer to the following sample.
https://codesandbox.io/s/drag-and-drop-as-optional-ts-sqzo11?file=/src/App.tsx
