### ISSUE TITLE
React 17 compatibility

### ISSUE THREAD

**Issue by kumar-parth** [minop1205/react-dnd-treeview#144]
Please add react 17 compatibility with this repo.

**Comment by kumar-parth** [comment]
fixed by adding --legacy-peer-deps

**Comment by kumar-parth** [comment]
closing this issue.

**Comment by kumar-parth** [comment]
TBD

**Comment by kumar-parth** [comment]
It seems it has a peer dependency on React 18. If you could add React 17 as well in the peer dependency, which would do wonders for me. Thanks again for this wonderful npm package. :)

**Comment by francoisroyer** [comment]
+1 for React 17 - thank you!

**Comment by minop1205** [comment]
Merged: https://github.com/minop1205/react-dnd-treeview/pull/152

**Comment by minop1205** [comment]
v3.2 のアルファ版の提供を開始しました。

```
npm i @minoru/react-dnd-treeview@alpha
```

このバージョンではReact 17.x も依存関係に加えていますので、React 17でも使用することが可能です。

NOTE:
React 17を使用する場合React DnDの最新版が利用できないようですので、React Dndは v15.x をインストールしてください。
https://github.com/react-dnd/react-dnd/issues/3423

**Comment by minop1205** [comment]
An alpha version of v3.2 is now available.

```
npm i @minoru/react-dnd-treeview@alpha
```

This version also includes React 17.x as a peer dependency, so it can be used with React 17.

NOTE:
If you use React 17, the latest version of React DnD is not available, so please install v15.x for React Dnd.
https://github.com/react-dnd/react-dnd/issues/3423
