### ISSUE TITLE
Invalid hook call. Hooks can only be called inside of the body of a function component.

### ISSUE THREAD

**Issue by Aagam41** [minop1205/react-dnd-treeview#160]
**Describe the bug**
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem. 

**To Reproduce**
1. ReactJs 18.2.0, React Dom 18.2.0
2. Produce the minimal setup of the treeview

**Expected behavior**
Hooks should be called inside FUNCTIONAL COMPONENTS

**Screenshots**
![Screenshot from 2022-10-23 11-17-00](https://user-images.githubusercontent.com/58718250/197376073-65b62e42-a7f7-4e0c-980e-80e3b84f85f8.png)
Issue is on line number 35, where useEffect is called inside useMemo.
\
![Screenshot from 2022-10-23 11-19-31](https://user-images.githubusercontent.com/58718250/197376130-9a3b14e5-e7ec-45f4-8c38-9b4877108830.png)

**Comment by kenbostoen** [comment]
How did you solve this?
