### ISSUE TITLE
Dragging problem

### ISSUE THREAD

**Issue by EugeneLobski** [minop1205/react-dnd-treeview#162]
Hi, I have a recurring bug. Sometimes, after dragging one item, the drag function is disabled. The cursor goes into edit mode and does not allow you to grab any element. The bug disappears after collapsing-expanding the parent node.

**Screenshots**
https://user-images.githubusercontent.com/784452/198878057-f6691c34-0fc8-45b3-8c63-0988850a3a9d.mp4

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 106.0.5249.119

**Comment by minop1205** [comment]
@EugeneLobski Thanks for the report.
What version of the package are you using? (e.g. @minoru/react-dnd-treeview@3.2.1)

If you are using an older version than the current latest version (v3.2.1), please check with the latest version.

**Comment by minop1205** [comment]
Merged: https://github.com/minop1205/react-dnd-treeview/pull/163

**Comment by minop1205** [comment]
@EugeneLobski I have fixed a code issue related to this problem. I have released a corrected package today as v3.2.2, so please install and try the latest version.

```
npm i @minoru/react-dnd-treeview@latest
```

If you still have problems, please reopen this Issue.

Thanks for your report.
