### ISSUE TITLE
NodeModel's passed type argument doesn't evaluate correctly

### ISSUE THREAD

**Issue by abrman** [minop1205/react-dnd-treeview#174]
**Describe the bug**
NodeModel's passed type argument doesn't evaluate correctly

**To Reproduce**
Create a `.d.ts` file and set its' content to be 
```
type NodeModel = import("@minoru/react-dnd-treeview").NodeModel;

type CustomNode = NodeModel<{
  test: boolean;
}>;
```

**Expected behavior**
CustomNode should have a type declaration other than `any`

**Screenshots**
![image](https://user-images.githubusercontent.com/6663260/206325356-d03c00aa-f2bc-4a58-a33e-aef90f3e7ca0.png)

**Comment by minop1205** [comment]
I think the reason is that the `NodeModel` declared on line 14 is no longer generics.
If you write the following, you should get the intended type.

```
type NodeModel = import("@minoru/react-dnd-treeview").NodeModel<{ test: boolean }>;
```

**Comment by abrman** [comment]
I wasn't aware of that! Thank you!
