### ISSUE TITLE
Can't import the named export 'Children' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by aslanalyiev** [minop1205/react-dnd-treeview#181]
**Describe the bug**
Just added your lib in a project(with TS) and got this error:

**To Reproduce**
1. Install the lib in project with TS;
2. Start a local dev server;
3. See error.

**Expected behavior**
Running/compile a proj without the error.

**Screenshots**
<img width="829" alt="image" src="https://user-images.githubusercontent.com/99654428/209565414-60361111-845d-4938-9c93-a05d16482c51.png">

**Comment by minop1205** [comment]
@aslanalyiev I could not reproduce the problem in my environment, but it seems to be caused by a dependent package.
The following Issue describes some solutions, would this be helpful?

https://github.com/framer/motion/issues/1525

**Comment by smith1511** [comment]
I'm also having this issue and none of the solutions for framer work for me :-(

**Comment by minop1205** [comment]
@smith1511 Perhaps it is due to the build configuration.
What are you using to build your application?
What type and version of build tool do you use?

**Comment by aslanalyiev** [comment]
Thank you for reply, yeah, I also found that it was this lib :( waiting for fixes :)
