### ISSUE TITLE
Custom style for each listitems element

### ISSUE THREAD

**Issue by BastienLairis** [minop1205/react-dnd-treeview#197]
Hi @minop1205 and thx for your awesome work ! 

I need to have custom style for each listitems element, currently classes key is actually waiting for **an object** I need it to waiting **for some sort of function** to have access to my node props.

I tried several ways but without success 😢

```js
function App() {
  return (
    <DndProvider backend={MultiBackend} options={getBackendOptions()}>
      <Tree
        tree={treeData}
        rootId={0}
        render={(node) => <div>{node.text}</div>}
        dragPreviewRender={(monitorProps) => (
          <div>{monitorProps.item.text}</div>
        )}
        // Actual behavior
        classes={{
          listItem: "bg-red",
        }}
        // what i would like to have
        classes={(node) => {
          return {
            listItem: `${node.text ? "bg-red" : "bg-blue"}`,
          };
        }}
      />
    </DndProvider>
  );
}

export default App;
```
![Capture d’écran 2023-04-07 à 17 50 01](https://user-images.githubusercontent.com/28651076/230639603-3e379651-d3a9-45e0-9196-fb5a8b46af7d.png)

**Comment by minop1205** [comment]
@BastienLairis  Thank you for your feature request!

This feature was implemented in v3.5.
It is currently available in the alpha version.

```
npm i @minoru/react-dnd-treeview@alpha
```

Among the classes properties, a callback function can be specified for listItem.

```
          <Tree
            {...otherProps}
            classes={{
              listItem: (node, params) => {
                return node.data?.fileType ? styles[node.data.fileType] : "";
              },
            }}
          />
```

For more information, please refer to the Storybook and CodeSandbox below.

CodeSandbox:
https://codesandbox.io/p/sandbox/dynamic-class-name-ts-thrng9?file=%2Fsrc%2FApp.tsx

Storybook:
https://minop1205.github.io/react-dnd-treeview/?path=/docs/basic-examples-dynamic-class-name--dynamic-class-name-story
