### ISSUE TITLE
Is there any way where we can add the radio button group for the nodes.

### ISSUE THREAD

**Issue by nilesh2b** [minop1205/react-dnd-treeview#207]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by minop1205** [comment]
@nilesh2b I think there are some ways to do this, but can you give me a concrete image of the screen? I may be able to provide a sample.

**Comment by nilesh2b** [comment]
As you see in the screenshot there are two value drivers but I am not able to create the two different radio button groups, there is single radio selection for entire list.
Please suggest!

**Comment by minop1205** [comment]
@nilesh2b 
As for radio buttons, they are not provided as a function of the treeview, but can be implemented by implementing logic outside of the treeview.

The sample below is an example of displaying sibling nodes as a single radio group.

https://codesandbox.io/s/radio-group-ts-rrvz3w?file=/src/App.tsx

I hope this is helpful.

**Comment by nilesh2b** [comment]
@minop1205 This is perfect example. thanks a ton for saving the day.

**Comment by nilesh2b** [comment]
@minop1205 Can we have default checked radio button for each group?
