### ISSUE TITLE
Add multiple new node at once.

### ISSUE THREAD

**Issue by nilesh2b** [minop1205/react-dnd-treeview#209]
@minop1205 I have been using this package from very long time and found very useful.

Can we add multiple nodes using dropdown list of nodes which will come from an API in the popup box of add new node?

**Comment by minop1205** [comment]
@nilesh2b 
Yes, it is possible.
No special method is needed, it should be possible by simply passing a new array to the tree property.

How you merge tree items is up to your application.

```
const newItems = [...oldItems, ...newItems];

<Tree tree={newItems} {. .otherProps} /> 
```

**Comment by nilesh2b** [comment]
@minop1205 Thanks again. I will apply this method and check.
