### ISSUE TITLE
node.droppable children check

### ISSUE THREAD

**Issue by gunheesssss** [minop1205/react-dnd-treeview#210]
node.droppable Is it possible to determine whether a parent has children or not?

https://github.com/minop1205/react-dnd-treeview/assets/126860189/d7d2967f-1429-4707-920d-c047443af2c1

I want to remove the arrow if there are no children.
And is it possible to set a maximum depth? 🥺🥺

**Comment by minop1205** [comment]
@gunheesssss 

See hasChild to see if a node has children.

https://github.com/minop1205/react-dnd-treeview#render-prop

![2023-10-12_10h27_02](https://github.com/minop1205/react-dnd-treeview/assets/3772820/1b67eff8-af31-476f-9a28-a20465d24204)

For the maximum depth, please refer to a similar Issue in the past.

https://github.com/minop1205/react-dnd-treeview/issues/127

**Comment by gunheesssss** [comment]
@minop1205 
Wow thank you for the really quick reply 🙏🙇🏻‍♂️
I should have looked better, I'm really sorry. 😭

Lastly, is there a search function?

**Comment by minop1205** [comment]
@gunheesssss 

Search API has been raised as another issue, but not yet addressed.
https://github.com/minop1205/react-dnd-treeview/issues/198
