### ISSUE TITLE
Should be dropped between 2 nodes

### ISSUE THREAD

**Issue by hungnguyen1412** [minop1205/react-dnd-treeview#46]
I mean, we have a tree likes that:
--node 1
--node 2
--node 3

I drag and drop the `node 3` between node 1 and node 2, it becomes:
--node 1
--node 3
--node 2

Thanks

**Comment by minop1205** [comment]
Thank you for your comments.
This issue is currently being addressed, but will be closed as it overlaps with the following issue.
https://github.com/minop1205/react-dnd-treeview/issues/41
