### ISSUE TITLE
Error during installation, React 17

### ISSUE THREAD

**Issue by Nerevar123** [minop1205/react-dnd-treeview#66]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When installed via 'npm install @minoru/react-dnd-treeview' got errors: 

`npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"*" from @testing-library/react@11.2.7
npm WARN   node_modules/@testing-library/react
npm WARN     @testing-library/react@"^11.2.7" from the root project        
npm WARN   6 more (react-dom, react-scripts, recoil, the root project, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.13" from react-dnd-multi-backend@6.0.2
npm WARN node_modules/react-dnd-multi-backend
npm WARN   react-dnd-multi-backend@"^6.0.2" from @minoru/react-dnd-treeview@1.5.3
npm WARN   node_modules/@minoru/react-dnd-treeview
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react-dnd-html5-backend@14.0.1
npm WARN node_modules/react-dnd-html5-backend
npm WARN   react-dnd-html5-backend@"^14.0.1" from @minoru/react-dnd-treeview@1.5.3
npm WARN   node_modules/@minoru/react-dnd-treeview
npm WARN     @minoru/react-dnd-treeview@"*" from the root project
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react-dnd-html5-backend@"^11.1.3" from react-dnd-multi-backend@6.0.2
npm WARN node_modules/react-dnd-multi-backend
npm WARN   react-dnd-multi-backend@"^6.0.2" from @minoru/react-dnd-treeview@1.5.3
npm WARN   node_modules/@minoru/react-dnd-treeview
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react-dnd-touch-backend@14.1.0
npm WARN node_modules/react-dnd-touch-backend
npm WARN   react-dnd-touch-backend@"^14.1.0" from @minoru/react-dnd-treeview@1.5.3
npm WARN   node_modules/@minoru/react-dnd-treeview
npm WARN     @minoru/react-dnd-treeview@"*" from the root project
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react-dnd-touch-backend@"^11.1.3" from react-dnd-multi-backend@6.0.2
npm WARN node_modules/react-dnd-multi-backend
npm WARN   react-dnd-multi-backend@"^6.0.2" from @minoru/react-dnd-treeview@1.5.3
npm WARN   node_modules/@minoru/react-dnd-treeview
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"*" from @testing-library/react@11.2.7
npm WARN   node_modules/@testing-library/react
npm WARN     @testing-library/react@"^11.2.7" from the root project
npm WARN   2 more (the root project, @minoru/react-dnd-treeview)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^16.13" from react-dnd-multi-backend@6.0.2
npm WARN node_modules/react-dnd-multi-backend
npm WARN   react-dnd-multi-backend@"^6.0.2" from @minoru/react-dnd-treeview@1.5.3
npm WARN   node_modules/@minoru/react-dnd-treeview
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"*" from @testing-library/react@11.2.7
npm ERR!   node_modules/@testing-library/react
npm ERR!     @testing-library/react@"^11.2.7" from the root project
npm ERR!   peer react@"17.0.2" from react-dom@17.0.2
npm ERR!   node_modules/react-dom
npm ERR!     peer react-dom@"*" from @testing-library/react@11.2.7
npm ERR!     node_modules/@testing-library/react
npm ERR!       @testing-library/react@"^11.2.7" from the root project
npm ERR!     react-dom@"^17.0.2" from the root project
npm ERR!     1 more (@minoru/react-dnd-treeview)
npm ERR!   5 more (react-scripts, recoil, the root project, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.13.1" from react-dnd-preview@6.0.2
npm ERR! node_modules/react-dnd-multi-backend/node_modules/react-dnd-preview
npm ERR!   react-dnd-preview@"^6.0.2" from react-dnd-multi-backend@6.0.2
npm ERR!   node_modules/react-dnd-multi-backend
npm ERR!     react-dnd-multi-backend@"^6.0.2" from @minoru/react-dnd-treeview@1.5.3
npm ERR!     node_modules/@minoru/react-dnd-treeview
npm ERR!       @minoru/react-dnd-treeview@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.`

Full report: 
[eresolve-report.txt](https://github.com/minop1205/react-dnd-treeview/files/7208132/eresolve-report.txt)

## Environment

<pre><code>
Libs:
- react version: 17.0.2

For Tooling issues:
- Node version: 16.5.0
- NPM version: 7.20.2
- Platform:  Windows

**Comment by minop1205** [comment]
@Nerevar123 Thanks for the error report!

I checked it in npm version you reported and found the error on my environment as well, so I fixed the dependency.

I've just published it as v1.5.4, so please try again.

```
npm install @minoru/react-dnd-treeview
```

**Comment by Nerevar123** [comment]
Now it works, thank you
