### ISSUE TITLE
Error: Expected drag drop context

### ISSUE THREAD

**Issue by Nerevar123** [minop1205/react-dnd-treeview#69]
The application crashes with this error:

![image](https://user-images.githubusercontent.com/65253367/135399290-35c2add5-04c3-4dc9-a749-13fb5eb50836.png)

Uninstalling and updating the package did not help, any ideas?

**Comment by Nerevar123** [comment]
Deleting node_modules and package-lock helped, can be closed

**Comment by minop1205** [comment]
@Nerevar123 
Thanks for the report.
I just tried it in a different environment and got the same phenomenon.
I will investigate.

**Comment by minop1205** [comment]
@Nerevar123 
I looked into this issue and found that there was a problem with the package dependencies.
I have fixed it and published it as v1.5.7.

If you still have any problems, please reopen this issue.
