### ISSUE TITLE
t.tree.filter is not a function

### ISSUE THREAD

**Issue by maxivane** [minop1205/react-dnd-treeview#74]
Hello, I use nodejs and this error is giving me, does anyone know how to solve it?

![image](https://user-images.githubusercontent.com/23021447/138358686-bf7c670a-784a-4d14-af06-e1af130ba971.png)

**Comment by minop1205** [comment]
@maxivane thank you for your report!
Please give me some more information to help me solve this problem.

- node version
- npm version
- this package version
- and other dependencies (in package.json) 

Or if there is any way to reproduce the error, please let me know.

**Comment by yagizhanavci** [comment]
If you are using any state manager that uses proxies like mobx , this error occurs. I have the same problem.
Mobx versions:
 "mobx": "^6.3.2",
 "mobx-react": "^7.2.0",

**Comment by minop1205** [comment]
@yagizhanavci Thanks for the detailed info!

I think it is probably due to the use of immer inside the Treeview package.

I've just published a version that doesn't use immer, can you try this one?

```
npm install --save @minoru/react-dnd-treeview@alpha
```

If everything looks good, I will include this fix in the next official release.

**Comment by minop1205** [comment]
I have published v1.5.11 today. This version does not use immer to generate new node arrays, so it does not conflict with libraries like mobx that use proxy.

If the problem still occurs, it would be helpful if you could give me a minimal configuration to reproduce it.
