### ISSUE TITLE
Unable to reorder items

### ISSUE THREAD

**Issue by themre** [minop1205/react-dnd-treeview#83]
Hi,
Great library! I was testing your examples and when I'm inside a folder, I'm unable to reorder files. Is this some config that I need to enable?
Example: https://codesandbox.io/s/minimum-configuration-ts-wjigd

**Comment by minop1205** [comment]
@themre 
To perform manual sorting, you need to use a combination of the following properties

- sort
- insertDroppableFirst
- canDrop
- dropTargetOffset
- placeholderRender

For more information, please refer to this section.
https://github.com/minop1205/react-dnd-treeview#manual-sort-with-placeholder

Here is a customized version of the sample you provided.
https://codesandbox.io/s/issue83-qqze5?file=/src/App.tsx

You can also use the `placeholderRender` property to help indicate where to insert the node.
https://codesandbox.io/s/placeholder-js-xhu2j?file=/src/App.jsx

I hope this is helpful.

**Comment by nosferatu500** [comment]
@minop1205 Thanks for the provided examples, very helpful. But is it possible to reorder with multiple selection? If I select multiple items and try to reorder the items, only the first selected item gets changed.
