### ISSUE TITLE
Add tree items on the fly and the main item (folder) is open

### ISSUE THREAD

**Issue by dgtllion** [minop1205/react-dnd-treeview#86]
Hi again @minop1205,

Im trying to add folder and 2 files on existing tree and i want that folder will be opened after i add it.
Is there a way how i can do that?

i tried this below but this dont work.
```
{
{id: 3, parent:1, text: 'Folder', droppable: true, isOpen: true},
{id: 4, parent:3, text: 'File 2', droppable: false},
{id: 5, parent:3, text: 'File 2', droppable: false},
}
```

**Comment by minop1205** [comment]
@dgtllion Is the following Open method useful?
https://github.com/minop1205/react-dnd-treeview#usage-to-open--close-methods

**Comment by dgtllion** [comment]
@minop1205 i try this example but it doesnt work.
Do i something wrong?

```
const [treeData, setTreeData] = useState(DUMMY_TREE_DATA);
const treeRef = useRef(null);

const handleOpen = (ev) => {
  setTreeData([...treeData,
    {id: 3, parent:1, text: 'Folder', droppable: true},
    {id: 4, parent:3, text: 'File 1', droppable: false},
    {id: 5, parent:3, text: 'File 2', droppable: false},]
  );
  treeRef.current.open(3);
}

<Tree ref={treeRef} tree={treeData} ... />

<button onClick={handleOpen}>Open specific folder</button>
```

**Comment by dgtllion** [comment]
Is there a way how i can open multiple folders at the same time?

Lets say i have a file that is on level 4. How i can open only parent folders where the file is located?
This is more from the search perspective. If i found a file on that level how can i open all other parent folders.

**Comment by minop1205** [comment]
@dgtllion Please refer to this page for more information.
https://codesandbox.io/s/issue86-3eb5p

The open/close methods can also specify an array.

Alternatively, these methods will only accept IDs that are already in the tree, so they will be ignored if run at the same time as setTreeData. Therefore, they need to be executed asynchronously using setTimeout, etc.

**Comment by dgtllion** [comment]
aaa i see the timeout did the trick, thanks!

Everything works! ;)
