### ISSUE TITLE
Error when using Tabs with different TreeViews

### ISSUE THREAD

**Issue by dbfernandes** [minop1205/react-dnd-treeview#88]
Hi @minop1205,

First of all, congratulations for the excellent package!

I'm trying to use Tabs (eg @mui/material/Tab) to navigate between different TreeViews. Let's say I have a set of tabs and each of them has a TreeView. When I open folders (or drag/drop files) from one tab, then go to another tab and go back to the previous tab, everything that was done in the first tab (open folders or drag/drop files) is undone.

I have created a codesandbox where this error can be verified: https://codesandbox.io/s/late-water-b7c7h

To reproduce the error, just follow these steps:

1) In the TreeView of the first Tab, open directories and drag/drop files from one folder to another.
2) Go to the second Tab, and then go back to the first Tab.
3) Everything that was done in the first tab (opening folders and moving files) was undone.

Thanks.

**Comment by dbfernandes** [comment]
Sorry, there was a problem in my code. I'm going to close this issue, reformulate the code, and then open the issue again.

**Comment by minop1205** [comment]
@dbfernandes Thanks for the message. I just looked at the code too, and it looks like the State is initialized because the TreeView component is unmounted when switching tabs.
