### ISSUE TITLE
prevent re-rendering for best performance render()

### ISSUE THREAD

**Issue by ayoub-root** [minop1205/react-dnd-treeview#94]
add memo function to prevent CustomNode rendering without any change@minoru/react-dnd-treeview

https://user-images.githubusercontent.com/29442800/149621206-1a1dad2f-047b-41c3-91b3-a6bbe4f69acd.mov

**Comment by maendros** [comment]
Hello . Was there a fix for that . I can still see that  CustomNode  is rerendered on hover.
